services:
  mysql:
    image: mysql:5.7
    container_name: petsql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=petclinic
      - MYSQL_ROOT_PASSWORD=   
      - MYSQL_ALLOW_EMPTY_PASSWORD=true  
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"  #was like this in documentaion
      - "./database_init_mw:/docker-entrypoint-initdb.d"   
      - "./savedata_mw:/var/lib/mysql"   

  adminer:
    image: adminer
    depends_on:
      - mysql
    container_name: petadminer
    ports:
      - "5051:8080"   

  petclinic:
   
   # image: mohamedwaleed77/depi_petclinic
   image: esraa114/depi_petclinic:latest 
    container_name: petapp
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic  
      SPRING_DATASOURCE_USERNAME: petclinic   
      SPRING_DATASOURCE_PASSWORD: petclinic   
    ports:
      - "5050:8080"   
  
