apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: petclinic
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: petclinic
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: petclinic
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: petclinic
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              value: petclinic
          image: mohamedwaleed77/depi_petclinic
          name: petapp
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
