---
  - name: Deploy Docker container on Ubuntu EC2
    hosts: ec2
    #connection: aws_ssm 
    become: yes
    vars:
      docker_image: "mohamedwaleed77/depi_petclinic:latest"
      container_name: "petclinic_app"
      host_port: 5050
      container_port: 8080
      venv_path: "/opt/ansible-venv" 
      ansible_python_interpreter: "{{ venv_path }}/bin/python"  # Updated to use venv path
    tasks:
      - name: Output the instance ID
        debug:
          msg: "The instance ID is {{ lookup('terraform', 'instance_id') }}"

      - name: Update apt cache
        apt:
          update_cache: yes
  
      - name: Install dependencies for Docker installation
        apt:
          name:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
          state: present
  
      - name: Install Python3 and venv
        apt:
          name:
            - python3
            - python3-venv
          state: present
  
      - name: Create a Python virtual environment
        command: "{{ ansible_python_interpreter }} -m venv {{ venv_path }}"
        args:
          creates: "{{ venv_path }}"
  
      - name: Install Docker SDK for Python in the virtual environment
        command: "{{ venv_path }}/bin/pip install docker"

      - name: Install boto3 in the virtual environment
        command: "{{ venv_path }}/bin/pip install boto3"

      - name: Download Docker installation script
        command: curl -fsSL https://get.docker.com -o get-docker.sh
  
      - name: Run Docker installation script
        command: sh get-docker.sh
  
      - name: Ensure Docker is running
        service:
          name: docker
          state: started
          enabled: true
  
      - name: Pull an image
        community.docker.docker_image:
          name: "{{ docker_image }}"
          source: pull
          pull:
            platform: amd64
        
      - name: Stop a container and remove any existing container
        community.docker.docker_container:
          name: "{{ container_name }}"
          state: absent
  
      - name: Run the new Docker container
        community.docker.docker_container:
          name: "{{ container_name }}"
          image: "{{ docker_image }}"
          state: started
          ports:
            - "{{ host_port }}:{{ container_port }}"
